[package]
name = "distance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
reqwest = "0.11.9"
structopt = "0.3.26"
thiserror = "1.0.30"
